/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mayur Shrivastava
 */
public class alogin extends javax.swing.JFrame {

    /**
     * Creates new form alogin
     */
    public alogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Schedules = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        tickets = new javax.swing.JButton();
        BookButton = new javax.swing.JButton();
        history = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel2.setPreferredSize(new java.awt.Dimension(1400, 900));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Schedules.setBackground(new java.awt.Color(102, 153, 255));
        Schedules.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Schedules.setText("Train Schedules");
        Schedules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchedulesActionPerformed(evt);
            }
        });
        jPanel2.add(Schedules, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 270, 120));

        exit.setBackground(new java.awt.Color(102, 153, 255));
        exit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel2.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 450, 260, 120));

        tickets.setBackground(new java.awt.Color(102, 153, 255));
        tickets.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tickets.setText("My Bookings");
        tickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketsActionPerformed(evt);
            }
        });
        jPanel2.add(tickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 280, 120));

        BookButton.setBackground(new java.awt.Color(102, 153, 255));
        BookButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BookButton.setText("Book your ticket");
        BookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookButtonActionPerformed(evt);
            }
        });
        jPanel2.add(BookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 280, 120));

        history.setBackground(new java.awt.Color(102, 153, 255));
        history.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        history.setText("Booking History");
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });
        jPanel2.add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 240, 290, 120));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/train.jpeg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 1660, 980));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, -50, 1660, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SchedulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchedulesActionPerformed
        Schedules sc= new Schedules();
        sc.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_SchedulesActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void BookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookButtonActionPerformed
        BookTicket bk = new BookTicket();
        bk.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BookButtonActionPerformed

    private void ticketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketsActionPerformed
        Bookings tk=new Bookings();
        tk.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ticketsActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
        TicketHistory th=new TicketHistory();
        th.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_historyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookButton;
    private javax.swing.JButton Schedules;
    private javax.swing.JButton exit;
    private javax.swing.JButton history;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton tickets;
    // End of variables declaration//GEN-END:variables
}
