/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mayur Shrivastava
 */
public class Ticket extends javax.swing.JFrame {

    /**
     * Creates new form Ticket
     */
    public Ticket() {
        initComponents();
    }
    int pr=(BookTicket.p);
    String pnrr=String.valueOf(pr);
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        from = new javax.swing.JTextField();
        p1phn = new javax.swing.JTextField();
        p3gender = new javax.swing.JTextField();
        p4gender = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        p3age = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        p2name = new javax.swing.JTextField();
        p1gender = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        p2age = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        p4name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        p4phn = new javax.swing.JTextField();
        p3phn = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        p1name = new javax.swing.JTextField();
        p2gender = new javax.swing.JTextField();
        pnr = new javax.swing.JTextField();
        gen = new javax.swing.JButton();
        p3name = new javax.swing.JTextField();
        p4age = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        p2phn = new javax.swing.JTextField();
        p1age = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("PNR NO.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 88, 29));
        getContentPane().add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 136, 36));
        getContentPane().add(p1phn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 340, 111, 36));
        getContentPane().add(p3gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 111, 36));
        getContentPane().add(p4gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 500, 111, 36));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("From");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 73, 29));
        getContentPane().add(p3age, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 111, 36));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Passenger3");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 136, 36));
        getContentPane().add(p2name, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 111, 36));
        getContentPane().add(p1gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, 111, 36));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 170, 73, 29));
        getContentPane().add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 136, 36));
        getContentPane().add(p2age, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 111, 36));

        exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 660, 132, 38));
        getContentPane().add(p4name, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 111, 36));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("To");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 61, 29));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Passenger2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 136, 36));
        getContentPane().add(p4phn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 500, 111, 36));
        getContentPane().add(p3phn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 450, 111, 36));

        home.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 660, 132, 38));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Passenger Details");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, 36));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Passenger1");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 139, 36));
        getContentPane().add(p1name, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 111, 36));
        getContentPane().add(p2gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 400, 111, 36));
        getContentPane().add(pnr, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 110, 30));

        gen.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        gen.setText("Generate Ticket");
        gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genActionPerformed(evt);
            }
        });
        getContentPane().add(gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 328, 66));
        getContentPane().add(p3name, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 111, 36));
        getContentPane().add(p4age, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 111, 36));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 210, 136, 36));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Passenger4");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 136, 36));
        getContentPane().add(p2phn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 400, 111, 36));
        getContentPane().add(p1age, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 111, 36));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genActionPerformed
        pnr.setText(pnrr);
        to.setText(BookTicket.to.getText());
        from.setText(BookTicket.from.getText());
        date.setText(BookTicket.datee.getText());
        p1name.setText(BookTicket.p1name.getText());
        p2name.setText(BookTicket.p2name.getText());
        p3name.setText(BookTicket.p3name.getText());
        p4name.setText(BookTicket.p4name.getText());
        p1age.setText(BookTicket.p1age.getText());
        p2age.setText(BookTicket.p2age.getText());
        p3age.setText(BookTicket.p3age.getText());
        p4age.setText(BookTicket.p4age.getText());
        p1gender.setText(BookTicket.p1gender.getText());
        p2gender.setText(BookTicket.p2gender.getText());
        p3gender.setText(BookTicket.p3gender.getText());
        p4gender.setText(BookTicket.p4gender.getText());
        p1phn.setText(BookTicket.p1phn.getText());
        p2phn.setText(BookTicket.p2phn.getText());
        p3phn.setText(BookTicket.p3phn.getText());
        p4phn.setText(BookTicket.p4phn.getText());                
    }//GEN-LAST:event_genActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        alogin al=new alogin();
        al.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JButton exit;
    private javax.swing.JTextField from;
    private javax.swing.JButton gen;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField p1age;
    private javax.swing.JTextField p1gender;
    private javax.swing.JTextField p1name;
    private javax.swing.JTextField p1phn;
    private javax.swing.JTextField p2age;
    private javax.swing.JTextField p2gender;
    private javax.swing.JTextField p2name;
    private javax.swing.JTextField p2phn;
    private javax.swing.JTextField p3age;
    private javax.swing.JTextField p3gender;
    private javax.swing.JTextField p3name;
    private javax.swing.JTextField p3phn;
    private javax.swing.JTextField p4age;
    private javax.swing.JTextField p4gender;
    private javax.swing.JTextField p4name;
    private javax.swing.JTextField p4phn;
    private javax.swing.JTextField pnr;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables
}
